version: "3.7"

services:
  web:
    build: .
  postgres: 
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455
    volumes:
      - "./postgres_data:/var/lib/postgresql"